network:
    version: 2
    renderer: networkd
    ethernets:
        enp0s3:
            dhcp4: yes
        enp0s8:
            dhcp4: no
            addresses: [192.168.127.3/24]
            gateway4: 192.168.127.2
            nameservers:
                addresses: [192.168.127.2,8.8.8.8]